@Todo.Api_HostAddress = http://localhost:5084
@TodoId = 00000000-0000-0000-0000-000000000000

POST {{Todo.Api_HostAddress}}/api/v1/todoitems
Content-Type: application/json

{
  "userId": "11111111-1111-1111-1111-111111111111",
  "description": "Pagar conta de luz",
  "priority": 1,
  "dueDate": "2026-04-30T00:00:00Z",
  "labels": ["financeiro", "mensal"]
}

###

GET {{Todo.Api_HostAddress}}/api/v1/todoitems?page=1&pageSize=5
Accept: application/json

###

GET {{Todo.Api_HostAddress}}/api/v1/todoitems/{{TodoId}}
Accept: application/json

###

PATCH {{Todo.Api_HostAddress}}/api/v1/todoitems/{{TodoId}}/completed

###

PATCH {{Todo.Api_HostAddress}}/api/v1/todoitems/{{TodoId}}/archived

###

POST {{Todo.Api_HostAddress}}/api/v1/todoitems/{{TodoId}}/copy
